insert into genre (code, name) values ('ACTION','Action');
insert into genre (code, name) values ('CARTOON','Tecknat');
insert into genre (code, name) values ('COMEDY','Komedi');
insert into genre (code, name) values ('DRAMA','Drama');
insert into genre (code, name) values ('FAMILY','Familj');
insert into genre (code, name) values ('ROMANCE','Romans');
insert into genre (code, name) values ('THRILLER','Thriller');
insert into genre (code, name) values ('WAR','Krig');
insert into genre (code, name) values ('WESTERN','Western');
