version: '3.7'

services:
 redis:
   image: redis:3.2
   ports:
     - 6379:6379
 httpd:
   image: httpd:2.4
   volumes:
     - .:/tmp/local
   ports:
     - 8888:80
   command: sh -c "cp -R /tmp/local/httpd/* /usr/local/apache2/conf && httpd-foreground"
 mysql:
   image: mysql:5.7
   volumes:
     - ${MYSQL_DATA_PATH}:/var/lib/mysql
     - .:/tmp/local
   ports:
     - 3366:3306
   command:
     - --character-set-server=utf8
     - --ft_min_word_len=2
     - --max_allowed_packet=900M
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: sbr2
     MYSQL_USER: sbr2
     MYSQL_PASSWORD: secret
     MYSQL_ROOT_HOST: 172.18.0.1
     TZ: "Europe/Stockholm"